language: node_js
node_js:
- 13
services:
- redis-server

before_install:
- openssl aes-256-cbc -K $encrypted_f57c64a0b291_key -iv $encrypted_f57c64a0b291_iv
  -in ./travis_deploy_key.enc -out ~/travis_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/travis_deploy_key
- echo -e "Host ipsaone.space\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ~/travis_deploy_key
- npm install pm2 -g
- ssh -i ~/travis_deploy_key travis@ipsaone.space pwd

deploy:
  - provider: script
    script: pm2 deploy ecosystem.config.js production
    on: 
      branch: master 
  - provider: script
    script: pm2 deploy ecosystem.config.js staging
    on: 
      branch: staging 

