language: node_js
node_js:
- 12
services:
- redis-server
deploy:
  skip-cleanup: true,
  provider: script,
  script: "./devops/build.sh"
  on:
    tags: true
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_f57c64a0b291_key -iv $encrypted_f57c64a0b291_iv
  -in travis_deploy_key.enc -out ~\/travis_deploy_key -d
